version: "3.0"

services:
  api:
    container_name: "api"
    volumes:
      - type: bind
        source: ./app
        target: /app
    build: .
    ports:
      - 8000:8000
  db:
    image: mysql/mysql-server:latest
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes" # rootアカウントをパスワードなしで作成
      TZ: "Asia/Tokyo" # タイムゾーンを日本時間に設定
    volumes:
      - mysql_data:/var/lib/mysql
    # MySQL8.0ではデフォルトが"caching_sha2_password"で、ドライバが非対応のため変更
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 33306:3306 # ホストマシンのポート33306を、docker内のポート3306に接続する
volumes:
  mysql_data:
